[package]
name = "my-up-app"
version = "0.1.0"
edition = "2021"

[dependencies]
up-transport-vsomeip = { path = "../up-transport-vsomeip-rust/up-transport-vsomeip" }
log = "0.4"
env_logger = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
up-rust = "0.9.0"
hello-world-protos = { path = "../up-transport-vsomeip-rust/example-utils/hello-world-protos" }
async-trait = "0.1"

[build-dependencies]
prost-build = "0.11"
tonic-build = "0.9"